### ISSUE TITLE
make release fail

### ISSUE THREAD

**Issue by pannous** [frankcash/go-lambda-ping#2]
GOOS=linux go build -o main
function.go:7:2: cannot find package "github.com/aws/aws-lambda-go/lambda" in any of:
	/usr/lib/go-1.6/src/github.com/aws/aws-lambda-go/lambda (from $GOROOT)
	/usr/local/go/src/github.com/aws/aws-lambda-go/lambda (from $GOPATH)
Makefile:2: recipe for target 'compile' failed
make: *** [compile] Error 1

**Comment by pannous** [comment]
`go get -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip` something?

**Comment by frankcash** [comment]
`go get github.com/aws/aws-lambda-go/lambda` should be the trick~!  

I will add to the README.

**Comment by frankcash** [comment]
https://github.com/frankcash/go-lambda-ping/commit/9c61e7fbf2b58f617b4c947be6ccb844679a3550
